### ISSUE TITLE
Lemur Web Interface "broken"?

### ISSUE THREAD

**Issue by RickB17** [Netflix/lemur#425] opened 2016-09-16 12:41 UTC
After following the quick start and standing up NGINX to deliver the static content, the web interface I receive is the attached image. Anyone else come across this?

![image](https://cloud.githubusercontent.com/assets/704271/18586168/44424fe6-7be9-11e6-958b-501f7b4ad46d.png)

**Comment by kevgliss** [comment] 2016-09-16 15:30
Do you see the python process running? What does it look like in your browser's console... any errors? It looks like two things are happening; 1) You're not getting any CSS and 2) The actual gunicorn webserver is not running.

**Comment by RickB17** [comment] 2016-09-16 18:58
Browser console:

![image](https://cloud.githubusercontent.com/assets/704271/18597859/eeb40a3a-7c1d-11e6-8aca-fd0747c5b9a7.png)

Uncaught ReferenceError: angular is not defined

**Comment by kevgliss** [comment] 2016-09-16 23:13
Did you get an errors when you were installing/building the javascript?

**Comment by RickB17** [comment] 2016-09-21 16:28
@kevgliss  Are you aware of a way to get that information from a log file post install?

**Comment by predakanga** [comment] 2016-09-29 06:19
Just encountered this issue myself - fixed by re-running bower (node_modules/.bin/bower install from the checkout directory) and then re-running gulp (node_modules/.bin/gulp install)

**Comment by predakanga** [comment] 2016-09-29 06:21
Also, an easy way to diagnose it - when bower components hadn't been installed, the "scripts/vendor-*.js" include was missing from index.html

**Comment by kevgliss** [comment] 2016-09-29 15:39
@predakanga Thanks for tracking this down... can you tell if this is just an error in bower or is there some build step that is acting flaky?

**Comment by RickB17** [comment] 2016-09-29 16:31
@predakanga  Thank you for sharing your findings and please excuse my n00bness when it comes to bower and gulp - I'm new to both of them.

**This command appeared to complete without issue:**
root@server:/www/lemur# ./node_modules/.bin/bower install --allow-root


**This command appears to fail because "install" is not in the gulp file**
root@server:/www/lemur# ./node_modules/.bin/gulp install
[12:24:55] Using gulpfile /www/lemur/gulpfile.js
[12:24:55] Task 'install' is not in your gulpfile
[12:24:55] Please check the documentation for proper gulpfile formatting

**Here's the gulpfile.js**
`
(lemur) root@pex-vm-lcm-01:/www/lemur# cat gulpfile.js
/**
 * Created by kglisson on 1/19/15.
 */
'use strict';

var gulp = require('gulp');

require('require-dir')('./gulp');

gulp.task('default', function () {
  var c = {
    reset: '\x1b[0m',
    bold: '\x1b[1m',
    green: '\x1b[32m',
    magenta: '\x1b[35m'
  };

  console.log('');
  console.log(c.green + c.bold + 'Main Commands' + c.reset);
  console.log(c.green + '-------------------------------------------' + c.reset);
  console.log(c.green + 'clean' + c.reset + ' - delete the .tmp/ and dist/ folders.');
  console.log(c.green + 'build' + c.reset + ' - execute the release build and output into the dist/ folder.');
  console.log(c.green + 'serve:dist' + c.reset + ' - execute the release build and output into the dist/ folder then run a local server for the files.');
  console.log(c.green + 'serve' + c.reset + ' - run JShint and LESS compiler to produce .tmp/ folder. Then serve up the app on a local server.');
  console.log('');
  console.log(c.green + c.bold + 'All Commands' + c.reset);
  console.log(c.green + '-------------------------------------------' + c.reset);
  console.log(Object.keys(gulp.tasks).sort().join('\n'));
  console.log('');

});
'

**Comment by predakanga** [comment] 2016-09-29 16:35
Got it - the issue *is* related to running as root, but it's not Bower's fault; your package.json already specifies --allow-root.

The problem is that when you run npm as root, it drops to the 'nobody' user before executing scripts: https://docs.npmjs.com/misc/scripts#user (via http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd)

This results in the following message during npm install, but does not cause npm to error out:
```
npm WARN cannot run in wd Lemur@ bower install --allow-root --config.interactive=false (wd=/usr/src/lemur)
```

In some circumstances I also encountered this stack trace which *does* error out of the make process:
```
Error: Bower components directory does not exist at bower_components
    at module.exports (/usr/src/lemur/node_modules/main-bower-files/lib/index.js:53:15)
    at injectHtml (/usr/src/lemur/gulp/build.js:147:21)
    at Gulp.<anonymous> (/usr/src/lemur/gulp/build.js:188:10)
    at module.exports (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /usr/src/lemur/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /usr/src/lemur/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/usr/src/lemur/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (/usr/src/lemur/node_modules/gulp-size/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:865:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

In terms of a solution, the easy way would be to modify the Makefile to call "npm install --unsafe-perm" instead of "npm install".

The technically correct way would probably be to detect running as root and exit immediately, as well as dropping --allow-root from bower in package.json

I've also [attached a log](https://github.com/Netflix/lemur/files/501196/make.out.txt) of a make run as root - it was created using `script`, so you probably want to use `cat` to play it back.

**Comment by predakanga** [comment] 2016-09-29 16:39
@RickB17 My bad, I meant `node_modules/.bin/gulp build`, not `node_modules/.bin/gulp install`.

I recommend a different fix though - change line 6 of the Makefile from `npm install` to `npm install --unsafe-perm`.

In my case there were a few other things that failed, who knows what other effects it might have had.

**Comment by RickB17** [comment] 2016-09-29 16:49
@predakanga  you're awesome. It works now!

Thank you!

**Comment by kevgliss** [comment] 2016-09-29 16:51
Ah, it seems I've run into this issue before...

See:
https://github.com/Netflix/lemur-docker/blob/master/web/Dockerfile#L31

What do we think would be the best way to approach this? A few options:
-Add a note in the install documentation that for containers the Make file won't work natively.
-Detect root in our make file and adjust npm accordingly, perhaps with a warning? I wouldn't want Lemur run as root except for in the container use case.

**Comment by predakanga** [comment] 2016-09-29 17:01
I'd recommend detecting root, personally. Warning against it would seem to fit npm's best practices, and it could potentially let you simplify your Dockerfile.

Also worth noting that it's not specific to containers - I just happened to be using a container as a staging area, but I do usually clone into /usr/src and run make as root even when not using a container.

**Comment by kevgliss** [comment] 2016-09-29 17:15
Sounds good to me I've opened up #430 to track this change.

**Closed by kevgliss** 2016-09-29 17:15 UTC
Labels: question
