### ISSUE TITLE
Lemur not adding OCSP and CRL url's to issued certificates

### ISSUE THREAD

**Issue by netcom-rs** [Netflix/lemur#3744] opened 2021-09-12 16:59 UTC
Hi guys. 

Does anyone have an issue with this? Plugin used is CFSSL. Everything else is fine. Intermediate certificate does have OCSP and CRL url's in attributes.

It seems like lemur is not sending correct profile to cfssl. If i am correct, it should send profile selected  in gui.

config.json is:

```
{
  "signing": {
    "default": {
         "ocsp_url": "http://ocsp.domain.com:8889",
         "crl_url": "https://crl.ddomain.com/crl",
         "expiry": "8760h",
         "usages": [
             "signing",
             "key encipherment",
             "client auth"
         ]
    },
    "profiles": {
      "intermediate": {
        "usages": [
            "signing",
            "digital signature",
            "key encipherment",
            "cert sign",
            "crl sign",
            "server auth",
            "client auth"
        ],
        "expiry": "8760h",
        "ca_constraint": {
            "is_ca": true,
            "max_path_len": 0,
            "max_path_len_zero": true
        }
      },
      "peer": {
        "usages": [
            "signing",
            "digital signature",
            "key encipherment",
            "client auth",
            "server auth"
        ],
        "expiry": "8760h"
      },
      "ocsp": {
        "usages": [
          "digital signature",
          "ocsp signing"
        ],
        "expiry": "8760h"
      },
      "server": {
        "usages": [
          "signing",
          "digital signature",
          "key encipherment",
          "server auth"
        ],
        "expiry": "8760h"
      },
      "client": {
        "usages": [
          "signing",
          "digital signature",
          "key encipherment",
          "client auth"
        ],
        "expiry": "8760h"
     }
    }
  }
}
```

**Comment by netcom-rs** [comment] 2021-09-14 17:54
Hello people of github :) anybody home? :))))))

**Comment by hosseinsh** [comment] 2021-09-17 16:25
Hi @netcom-rs, 

CFSSL [plugin](https://github.com/Netflix/lemur/blob/8dff7b982088607ded1fc1753b356607bf851baf/lemur/plugins/lemur_cfssl/plugin.py) is a community contribution, which I am not familiar with. 

Glancing at the code, looks like the certificate request data mostly consists of the CSR. You might need to add additional metadata to indicate OCSP or CRL, or the algorithms to be used, similar to how the DigiCert [request](https://github.com/Netflix/lemur/blob/c8d53e960af8f02fa10a3efb11b24d39d01b8d74/lemur/plugins/lemur_digicert/plugin.py#L155-L192) is being constructed.

Also often, you can configure your profile with the CA, and just send the profile_name in your request, similar to [here](https://github.com/Netflix/lemur/blob/c8d53e960af8f02fa10a3efb11b24d39d01b8d74/lemur/plugins/lemur_digicert/plugin.py#L175)

Happy to review a PR, however, we don't have the option to test it.

**Comment by netcom-rs** [comment] 2021-09-17 18:34
@hosseinsh I agree with what you said.

 Csr is constructed in lemur by selecting either predefined profile or manually ticking x509 extensions. After that, csr is sent to cfssl for signing. The certificate then comes back from cfssl into lemur database. Either the csr is not constructed well on lemur side(with wrong x509 attributes) or the cfssl is not properly signing. 

The question is, how cfssl knows which profile to select? Or does it use default signing profile?

**Comment by jmcrawford45** [comment] 2023-09-06 21:33
The default is currently used, but there's a feature request out for supporting multiple profiles. Closing this as a duplicate of https://github.com/Netflix/lemur/issues/3950

**Closed by jmcrawford45** 2023-09-06 21:33 UTC
