### ISSUE TITLE
Update nodejs to LTS

### ISSUE THREAD

**Issue by wyaeld** [Netflix/lemur#561] opened 2016-12-05 22:25 UTC
@kevgliss what do you think about updating the node runtime to the current LTS.  The older versions aren't supported past end of this year

- would you be happy to jump straight to 6.9 LTS?
- which packages would need to be updated?
- what needs to be tested to ensure its all working?

I can take a stab at it, but prefer to discuss first

**Comment by kevgliss** [comment] 2016-12-05 23:12
I'm all for updating dependencies, we just recently updated all of our python dependencies. Node is really only used by gulp to generate the final form of the angular application. The javascript side of things aren't nearly well tested.

I would assume that updating node should be relatively straightforward and if you can ensure the following steps complete without error I would accept a PR.

1) npm install
   1a) npm install --unsafe-perm # for root users assuming behaviour does not change in the current nodejs
2) node_modules/.bin/gulp build
3) node_modules/.bin/gulp package
4) node_modules/.bin/gulp serve

**Comment by kevgliss** [comment] 2016-12-13 00:59
@wyaeld Not sure if you have started work on this, but its been bumped on in priority as recent builds have started failing... still not quite sure of the cause? Change in npm? Something else? Will be digging around to see if I can find the issue.

**Comment by wyaeld** [comment] 2016-12-13 01:33
@kevgliss have some progress I've been working on, will push it up tonight.  Was experimenting a little

**Comment by kevgliss** [comment] 2016-12-13 01:52
Cool, I put together #585 . Essentially it just upgrades everything and removes the engine requirement... *it works* (both gulp serve and gulp build run). But I still need to do some additionally testing. Look forward to what you have come home with.

**Comment by kevgliss** [comment] 2016-12-13 21:25
I pushed this would and it seems okay. Closing for now but feel free to submit any PRs that improve my node stuff :-).

**Closed by kevgliss** 2016-12-13 21:25 UTC
Labels: enhancement, help wanted
