### ISSUE TITLE
Ensure that Lemur roles are assigned correctly via Ping provider.

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#966] opened 2017-10-09 17:17 UTC
There are cases where the Ping provider is assigning all of the known google group roles, but Lemur specific roles are being lost during login.

**Comment by SecurityInsanity** [comment] 2017-12-07 23:51
We also seem to be running into this with LDAP. I think it has something to do with:

https://github.com/Netflix/lemur/blob/master/lemur/auth/ldap.py#L68

But I'll be taking a look into this for ldap. I'm not to familiar with the ping provider, but I'll try to test that as well.

**Comment by SecurityInsanity** [comment] 2017-12-08 16:20
I've confirmed that the `if ur.authority_id` is what's causing the problem. The built in roles do not get generated with an authority id. It seems these lines for ldap were copied from the ping provider, and the ping provider has had it since the initial commit.

Is there any reason to keep this check at all @kevgliss ? E.g. should we try to do something like (pseudo-code: `if ur.authority_id || ur.name in this list of prebuilt roles`)? Or is it okay to just remove the check altogether.

**Comment by kevgliss** [comment] 2017-12-08 17:30
I believe that was added so that authority based roles do not get removed:

https://github.com/Netflix/lemur/blob/master/lemur/users/service.py#L67

That the Lemur specific roles *wouldn't* be removed. It looks like this had the intended affect for *authority* based roles. But not for more general roles (admin, operator, etc,.)

It looks like we need some way to differentiate "Lemur" roles (admin, operator, etc.,) "Authority" roles (roles with authority.id) and third-party roles. It seems like the last two are okay but the first is not properly defined.

**Comment by SecurityInsanity** [comment] 2017-12-08 17:36
I agree it seems the first one doesn't have an identifier that makes it easy to define. 

However for the purpose of this issue, is there ever a reason we wouldn't want all roles the user currently has assigned to come over? If we can just remove that check for now so all roles come over on login, then figure out how to define built in roles if needed later. I don't think we need the ability to differentiate here, we should just bring them all over.

**Comment by kevgliss** [comment] 2017-12-08 18:00
If we do that, how do we reconcile with roles removed by the third-party?

**Comment by SecurityInsanity** [comment] 2017-12-08 18:02
If the role was removed by the third party, wouldn't it not be on the user object anymore? Since we fetch the user object on login,we'd always have their latest set of roles as shown in the UI of lemur.

**Comment by kevgliss** [comment] 2017-12-08 18:19
Third-party in case means ping/ldap, not through the Lemur UI. We use google groups passed to us from our ping provider to tell us which groups the user is currently in. We then take that list of groups/roles and determine if any were removed by comparing it to the user's current roles in Lemur (sans any authority roles). 

I think the cleanest way to handle this is to remove the authority.id check you mentioned but also add a new field to the "role" table named `third_party=bool`. Upon signing we can ensure all roles passed to us by our provider are marked/created as `third_party=True`. The reconciliation check is then more clearly defined by roles as managed outside of Lemur. 

Does that make sense?

**Comment by SecurityInsanity** [comment] 2017-12-08 18:20
Ah! I get where my disconnect was. I see the problem now. Alright, I'll work on getting this worked into lemur.

**Closed** 2017-12-11 21:51 UTC
Labels: bug
